"""Initial migration

Revision ID: 0e53c01be55a
Revises: 
Create Date: 2026-10-06 08:24:31.019480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import db.models


# revision identifiers, used by Alembic.
revision: str = '0e53c01be55a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carbon_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('polled_at', db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('reading_datetime', db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('region', sa.String(length=8), nullable=False),
    sa.Column('carbon_intensity_gco2eq_kwh', sa.Float(), nullable=False),
    sa.Column('is_estimated', sa.Boolean(), nullable=False),
    sa.Column('estimation_method', sa.String(length=128), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carbon_snapshots_id'), 'carbon_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_carbon_snapshots_polled_at'), 'carbon_snapshots', ['polled_at'], unique=False)
    op.create_table('dispatch_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('region', sa.String(length=8), nullable=False),
    sa.Column('hours', sa.Integer(), nullable=False),
    sa.Column('industrial_count', sa.Integer(), nullable=False),
    sa.Column('battery_count', sa.Integer(), nullable=False),
    sa.Column('cost_saved_usd', sa.Float(), nullable=True),
    sa.Column('co2_saved_kg', sa.Float(), nullable=True),
    sa.Column('peak_shaved_kw', sa.Float(), nullable=True),
    sa.Column('model_used', sa.String(length=64), nullable=True),
    sa.Column('triggered_by', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispatch_runs_id'), 'dispatch_runs', ['id'], unique=False)
    op.create_index(op.f('ix_dispatch_runs_timestamp'), 'dispatch_runs', ['timestamp'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('role', sa.Enum('admin', 'grid_operator', 'facility_manager', name='userrole'), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', db.models.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_dispatch_runs_timestamp'), table_name='dispatch_runs')
    op.drop_index(op.f('ix_dispatch_runs_id'), table_name='dispatch_runs')
    op.drop_table('dispatch_runs')
    op.drop_index(op.f('ix_carbon_snapshots_polled_at'), table_name='carbon_snapshots')
    op.drop_index(op.f('ix_carbon_snapshots_id'), table_name='carbon_snapshots')
    op.drop_table('carbon_snapshots')
    # ### end Alembic commands ###
